### PROJETO	
GET http://localhost:3000/projetos


### CREATE
POST http://localhost:3000/projetos
content-type: application/json

{
    "nomeProjeto": "AgriCont",
    "autorProjeto": "Cláudia ",
    "emailUsuario": "agricont@gmail.com",
    "tecnologias": "HTML, CSS, BootStrap, NET C#,SQLServer",
    "Finalizado": false,
    "descricaoProjeto": "O objetivo deste projeto é facilitar o controle patrimonial",
    "descricaoVaga": "Empresa: Juninho - Dev fullstack jr -  Salário: À Combinar",
    "repositorio": "github.com/AgriCont",
    "quantidadeParticipante": 1,
    "participantesProjeto": [
      "Carolina Laurindo",
      "Douglas Raynner",
      "Jéssica Grimaldi",
      "Jeferson Queiroz",
      "Karen Noguti"
    ]
}

### UPDATE
PUT http://localhost:3000/projetos/2
content-type: application/json

{
    "id":3,
    "nomeProjeto": "AgriCont",
    "autorProjeto": "Cláudia ",
    "emailUsuario": "agricont@gmail.com",
    "tecnologias": "HTML, CSS, BootStrap, SQLServer",
    "Finalizado": false,
    "descricaoProjeto": "O objetivo deste projeto é facilitar o controle patrimonial",
    "descricaoVaga": "Empresa: Juninho - Dev fullstack jr -  Salário: À Combinar",
    "repositorio": "github.com/AgriCont",
    "quantidadeParticipante": 5,
    "participantesProjeto": [
      "Carolina Laurindo",
      "Douglas Raynner",
      "Jéssica Grimaldi",
      "Jeferson Queiroz",
      "Karen Noguti"
    ]
}


### GET PROJETO
GET http://localhost:3000/projetos/2

### DELETE PROJETO
DELETE http://localhost:3000/projetos/2
